# -*- coding: utf-8 -*-
"""BoW.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iY_GEHsrj1xJOOU3qbc963xWS47oMpMc
"""

!pip install  konlpy

# Open-source Korean Text Processor
from konlpy.tag import Okt # Open Korean Text

okt = Okt()

def build_bow(doc):

    # 입력 문장에서 마침표 제거
    doc = doc.replace('.', '')

    # 형태소 분석으로 문장 토큰화
    tokenized_doc = okt.morphs(doc)

    # 단어와 인덱스를 저장할 딕셔너리 생성
    word_to_index = {}

    # Bag of Words 벡터 생성을 위한 리스트 생성
    bow = []

    # 마침표 제거되고 토큰화된 단어에 대한 반복 작업
    for word in tokenized_doc:
        if word not in word_to_index.keys():
            # 새로운 단어를 딕셔너리에 추가하고 인덱스를 할당
            word_to_index[word] = len(word_to_index)

            # 새로운 단어의 출현 횟수인 기본값 1을 bow 리스트 마지막 위치에 추가
            bow.insert(len(word_to_index) -1, 1)
        else:
            # 이미 등장한 단어의 인덱스를 가져온다.
            index = word_to_index.get(word)
            # 해당 단어의 bow 리스트의 값을 1 증가시킨다.
            bow[index] = bow[index] + 1

    return word_to_index, bow

doc1 = "저는 인공지능 분야에 취업할 계획입니다. 인공지능은 재미있습니다. 인공지능 분야에서도 특히 자연어 처리에 관심이 있습니다."

vocab, bow = build_bow(doc1) # word_to_index를 vocab 변수에, bow를 bow 변수에 저장
print('단어: ', vocab)
print('Bag of Words Vector: ', bow)

