# -*- coding: utf-8 -*-
"""TF-IDF_Sklearn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nk8l2nM_5pYCrZgUZBAkSxi5_AR9IeJZ
"""

from sklearn.feature_extraction.text import CountVectorizer

documents = [
    "과일에는 비타민C가 다량 함유되어 있다.", 
    "비타민C를 채우기 위해서는 다양한 방법이 있다. 비타오백을 마시는 방법, 비타민C가 함유된 건강보조식품을 먹는 방법 등.",
    "동남아에 가면 대체로 한국보다 과일을 저렴하게 살 수 있다.",
    "비타민은 여러 종류가 있다.  비타민A, 비타민B, 비타민C, 비타민D...",
    "한라봉은 제주 특산품으로, 많은 사람들이 즐겨 찾는 과일이다."
]

vectorizer = CountVectorizer()

# 코퍼스로부터 각 단어의 빈도수를 기록
print(vectorizer.fit_transform(documents).toarray())

# 각 단어와 맵핑된 인덱스 출력
print(vectorizer.vocabulary_)

# 사이킷런은 TF-IDF를 자동 계산해주는 TfidfVectorizer를 제공한다.
from sklearn.feature_extraction.text import TfidfVectorizer

documents = [
    "과일에는 비타민C가 다량 함유되어 있다.", 
    "비타민C를 채우기 위해서는 다양한 방법이 있다. 비타오백을 마시는 방법, 비타민C가 함유된 건강보조식품을 먹는 방법 등.",
    "동남아에 가면 대체로 한국보다 과일을 저렴하게 살 수 있다.",
    "비타민은 여러 종류가 있다.  비타민A, 비타민B, 비타민C, 비타민D...",
    "한라봉은 제주 특산품으로, 많은 사람들이 즐겨 찾는 과일이다."
]

tfidfv = TfidfVectorizer().fit(documents)
print(tfidfv.transform(documents).toarray())
print(tfidfv.vocabulary_)

import pandas as pd
tfidfv.vocabulary_

result = tfidfv.transform(documents).toarray()
tfidf_ = pd.DataFrame(result, columns = tfidfv.vocabulary_)
tfidf_

